//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizNet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int AID { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> QUESTION_ID { get; set; }
        public Nullable<short> IS_CORRECT { get; set; }
        public DateTime CREATION_TIME { get; set; }

    }
}
